@startuml
actor Citizen
participant "xShare Yellow Button" as xShare
participant "Citizen's Storage" as Storage

==== Citizen authentication (pre-condition) ====
group #00FF00 Citizen Authentication
Citizen -[#blue]> Citizen: Citizen Authenticates in the user interface
end group

==== Search and Select Health Information ====
group Search and Select Citizen's Health data
Citizen -> xShare: Search Citizen's Health Data
activate xShare
xShare -> xShare: Search Citizen's Health Data
return: Shows Citizen's available Health Data
Citizen -> xShare: Selects health data to download or share
activate xShare
end group

==== Retrieve and Format Health Information ====
group Retrieve and Format Citizen's Health data
xShare-> xShare: Retrieve Citizen's Health Data
xShare-> xShare: EEHRxF data
end group

==== Selects Data Transformation Option ====
opt select Data Transformation option
Citizen -> xShare: Selects transformation option (human-readable format, \n anonymisation, password protection, translation, digital signature)
xShare -> xShare: Transformed data
end opt

==== Download Health Information ====
group Download Citizen's Health Information
Citizen -> xShare: Downloads Citizen's Health Data
xShare -> Storage: Citizen's Health Information is stored
deactivate xShare
end group

@enduml